[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--production=false"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache optimization for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache optimization for images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# HTML caching
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=31536000, must-revalidate"